   ## 컨텐츠 기반 추천 시스템 - TMDB 5000 Movie Dataset 

In [11]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
import koreanize_matplotlib
import json

In [12]:
data = pd.read_csv("https://raw.githubusercontent.com/haram4th/ablearn/main/tmdb_5000_movies.csv",encoding="utf-8")

In [13]:
pd.set_option("display.max_columns",None) #컬럼 요약삭제 

In [14]:
data.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   homepage              1712 non-null   object 
 3   id                    4803 non-null   int64  
 4   keywords              4803 non-null   object 
 5   original_language     4803 non-null   object 
 6   original_title        4803 non-null   object 
 7   overview              4800 non-null   object 
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object 
 10  production_countries  4803 non-null   object 
 11  release_date          4802 non-null   object 
 12  revenue               4803 non-null   int64  
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object 
 15  status               

In [16]:
def add_genre_name(j):
    genres = []
    ar = json.loads(j)
    for a in ar:
        genres.append(a.get("name"))
    return " ".join(genres)
        

In [17]:
def lang_get(x):
    lang = [] 
    lan = json.loads(x)
    for i in lan:
        lang.append(i.get("iso_639_1"))
    return ",".join(lang)

In [18]:
def key_get(x):
    keyword = []
    key = json.loads(x)
    for i in key:
        keyword.append(i.get("name"))
    return " ".join(keyword)

In [19]:
data["genres"] = data["genres"].apply(lambda x: add_genre_name(x))

In [20]:
data["spoken_languages"] = data["spoken_languages"].apply(lambda x:lang_get(x))

In [21]:
data["keywords"] = data["keywords"].apply(lambda x: key_get(x))

In [22]:
data["production_companies"].apply(lambda x: key_get(x))

0       Ingenious Film Partners Twentieth Century Fox ...
1       Walt Disney Pictures Jerry Bruckheimer Films S...
2                            Columbia Pictures Danjaq B24
3       Legendary Pictures Warner Bros. DC Entertainme...
4                                    Walt Disney Pictures
                              ...                        
4798                                    Columbia Pictures
4799                                                     
4800    Front Street Pictures Muse Entertainment Enter...
4801                                                     
4802            rusty bear entertainment lucky crow films
Name: production_companies, Length: 4803, dtype: object

In [23]:
data

budget                                    genres  \
0     237000000  Action Adventure Fantasy Science Fiction   
1     300000000                  Adventure Fantasy Action   
2     245000000                    Action Adventure Crime   
3     250000000               Action Crime Drama Thriller   
4     260000000          Action Adventure Science Fiction   
...         ...                                       ...   
4798     220000                     Action Crime Thriller   
4799       9000                            Comedy Romance   
4800          0             Comedy Drama Romance TV Movie   
4801          0                                             
4802          0                               Documentary   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     culture clash future space war space colony so...                en   
1     ocean drug abuse exotic island east india trad...                en   
2     spy based on novel secret agent sequel mi6 bri...                en   
3     dc comics crime fighter terrorist secret ident...                en   
4     based on novel mars medallion space travel pri...                en   
...                                                 ...               ...   
4798  united states–mexico barrier legs arms paper k...                es   
4799                                                                   en   
4800  date love at first sight narration investigati...                en   
4801                                                                   en   
4802               obsession camcorder crush dream girl                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577   
1     Captain Barbossa, long believed to be dead, ha...  139.082615   
2     A cryptic message from Bond’s past sends him o...  107.376788   
3     Following the death of District Attorney Harve...  112.312950   
4     John Carter is a war-weary, former military ca...   43.926995   
...                                                 ...         ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he first saw ...    1.929883   

                                   production_companies  \
0     [{"name": "Ingenious Film P

In [24]:
df = data[["id","title","genres","vote_average","popularity","keywords","overview"]]

df

id                                     title  \
0      19995                                    Avatar   
1        285  Pirates of the Caribbean: At World's End   
2     206647                                   Spectre   
3      49026                     The Dark Knight Rises   
4      49529                               John Carter   
...      ...                                       ...   
4798    9367                               El Mariachi   
4799   72766                                 Newlyweds   
4800  231617                 Signed, Sealed, Delivered   
4801  126186                          Shanghai Calling   
4802   25975                         My Date with Drew   

                                        genres  vote_average  popularity  \
0     Action Adventure Fantasy Science Fiction           7.2  150.437577   
1                     Adventure Fantasy Action           6.9  139.082615   
2                       Action Adventure Crime           6.3  107.376788   
3                  Action Crime Drama Thriller           7.6  112.312950   
4             Action Adventure Science Fiction           6.1   43.926995   
...                                        ...           ...         ...   
4798                     Action Crime Thriller           6.6   14.269792   
4799                            Comedy Romance           5.9    0.642552   
4800             Comedy Drama Romance TV Movie           7.0    1.444476   
4801                                                     5.7    0.857008   
4802                               Documentary           6.3    1.929883   

                                               keywords  \
0     culture clash future space war space colony so...   
1     ocean drug abuse exotic island east india trad...   
2     spy based on novel secret agent sequel mi6 bri...   
3     dc comics crime fighter terrorist secret ident...   
4     based on novel mars medallion space travel pri...   
...                                                 ...   
4798  united states–mexico barrier legs arms paper k...   
4799                                                      
4800  date love at first sight narration investigati...   
4801                                                      
4802               obsession camcorder crush dream girl   

                                               overview  
0     In the 22nd century, a paraplegic Marine is di...  
1     Captain Barbossa, long believed to be dead, ha...  
2     A cryptic message from Bond’s past sends him o...  
3     Following the death of District Attorney Harve...  
4     John Carter is a war-weary, former military ca...  
...                                                 ...  
4798  El Mariachi just wants to play his guitar and ...  
4799  A newlywed couple's honeymoon is upended by th...  
4800  "Signed, Sealed, Delivered" introduces a dedic...  
4801  When ambitious New York attorney Sam is sent t...  
4802  Ever since the second grade when he first saw ...  

[4803 rows x 7 columns]

## genres의 단어 벡터화  / 코사인유사도 이용 
* 비슷한 장르를 가진 행을 찾고 , 유사도가 높은 행을 기준으로 내림차순 정렬


In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
cv = CountVectorizer(ngram_range=(1,2))
genre_mat = cv.fit_transform(df["genres"])
print(genre_mat)

  (0, 0)	1
  (0, 16)	1
  (0, 124)	1
  (0, 232)	1
  (0, 138)	1
  (0, 1)	1
  (0, 24)	1
  (0, 135)	1
  (0, 233)	1
  (1, 0)	1
  (1, 16)	1
  (1, 124)	1
  (1, 24)	1
  (1, 125)	1
  (2, 0)	1
  (2, 16)	1
  (2, 1)	1
  (2, 64)	1
  (2, 20)	1
  (3, 0)	1
  (3, 64)	1
  (3, 90)	1
  (3, 234)	1
  (3, 4)	1
  (3, 68)	1
  :	:
  (4796, 90)	1
  (4796, 234)	1
  (4796, 106)	1
  (4796, 144)	1
  (4797, 234)	1
  (4797, 153)	1
  (4797, 157)	1
  (4798, 0)	1
  (4798, 64)	1
  (4798, 234)	1
  (4798, 4)	1
  (4798, 78)	1
  (4799, 44)	1
  (4799, 214)	1
  (4799, 58)	1
  (4800, 90)	1
  (4800, 44)	1
  (4800, 214)	1
  (4800, 104)	1
  (4800, 50)	1
  (4800, 250)	1
  (4800, 182)	1
  (4800, 251)	1
  (4800, 229)	1
  (4802, 80)	1


In [27]:
genre_mat.shape

(4803, 276)

## 코사인 유사도 사용 
* genre_mat의 유사도 산출 후 , genre_sim에 저장 
* 비슷한 장르 영화를 찾기 위해 계산 
* 코사인 유사도는 주로 문자, 문서의 유사도 계산에 사용됨

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
genre_sim = cosine_similarity(genre_mat,genre_mat)
print(genre_sim.shape)
print(genre_sim[:2])

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]]


In [30]:
a = np.array([1.5,0.2,4.2,2.5])
s = a.argsort()
print(s[::-1])

[2 3 0 1]


In [31]:
[5,9,7,12][::-1]

[12, 7, 9, 5]

In [32]:
sorted_gerne_sim = genre_sim.argsort()[:,::-1]

In [33]:
sorted_gerne_sim[:1]

array([[   0, 3494,  813, ..., 3038, 3037, 2401]], dtype=int64)

In [34]:
df[df["title"] == "Superman"].index.values

array([813], dtype=int64)

In [35]:
def find_sim_movie(df,sorted_genre_sim,title_name,top_n=10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    similar_indexes = sorted_genre_sim[title_index, :(top_n)]
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    return df.iloc[similar_indexes]

In [36]:
find_sim_movie(df,sorted_gerne_sim,"Superman III",10)

[[1296    0   14  813  870 3494   46 1652 1932 1191]]


id                                      title  \
1296    9531                               Superman III   
0      19995                                     Avatar   
14     49521                               Man of Steel   
813     1924                                   Superman   
870     8536                                Superman II   
3494   27549  Beastmaster 2: Through the Portal of Time   
46    127585                 X-Men: Days of Future Past   
1652   14164                       Dragonball Evolution   
1932   24264                                     Sheena   
1191   11551                             Small Soldiers   

                                                 genres  vote_average  \
1296    Comedy Action Adventure Fantasy Science Fiction           5.3   
0              Action Adventure Fantasy Science Fiction           7.2   
14             Action Adventure Fantasy Science Fiction           6.5   
813            Action Adventure Fantasy Science Fiction           6.9   
870            Action Adventure Fantasy Science Fiction           6.5   
3494           Action Adventure Fantasy Science Fiction           4.6   
46             Action Adventure Fantasy Science Fiction           7.5   
1652  Action Adventure Fantasy Science Fiction Thriller           2.9   
1932    Action Adventure Comedy Fantasy Science Fiction           5.0   
1191    Comedy Adventure Fantasy Science Fiction Action           6.2   

      popularity                                           keywords  \
1296   22.164202  saving the world dc comics super computer iden...   
0     150.437577  culture clash future space war space colony so...   
14     99.398009  saving the world dc comics superhero based on ...   
813    48.507081  saving the world journalist dc comics crime fi...   
870    30.515175  saving the world dc comics sequel superhero ba...   
3494    1.478505  based on novel time travel sequel psychotronic...   
46    118.078691  1970s mutant time travel marvel comic based on...   
1652   21.677732  karate superhero revenge dragon duringcreditss...   
1932    4.020194  africa mercenary adventure female hero jungle ...   
1191   23.088571  defense industry toy shop technical toy soldie...   

                                               overview  
1296  Aiming to defeat the Man of Steel, wealthy exe...  
0     In the 22nd century, a paraplegic Marine is di...  
14    A young boy learns that he has extraordinary p...  
813   Mild-mannered Clark Kent works as a reporter a...  
870   Three escaped criminals from the planet Krypto...  
3494  Mark Singer returns as Dar, the warrior who ca...  
46    The ultimate X-Men ensemble fights a war for t...  
1652  The young warrior Son Goku sets out on a quest...  
1932  Sheena's white parents are killed while on Saf...  
1191  When missile technology is used to enhance toy...

In [37]:
import joblib 


In [40]:
joblib.dump(data,"movie_data")

['movie_data']

In [41]:
joblib.dump(sorted_gerne_sim,"move_similarity")

['move_similarity']